### ISSUE TITLE
time out

### ISSUE THREAD

**Issue by Kayzh3r** [1sw/Agentuino#1]
Microsoft Windows [Versión 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Reservados todos los derechos.

C:\Users\Ignazio F.Finazzi>ping 192.168.1.105

Haciendo ping a 192.168.1.105 con 32 bytes de datos:
Respuesta desde 192.168.1.105: bytes=32 tiempo<1m TTL=128
Respuesta desde 192.168.1.105: bytes=32 tiempo<1m TTL=128
Respuesta desde 192.168.1.105: bytes=32 tiempo<1m TTL=128
Respuesta desde 192.168.1.105: bytes=32 tiempo<1m TTL=128

Estadísticas de ping para 192.168.1.105:
    Paquetes: enviados = 4, recibidos = 4, perdidos = 0
    (0% perdidos),
Tiempos aproximados de ida y vuelta en milisegundos:
    Mínimo = 0ms, Máximo = 0ms, Media = 0ms

C:\Users\Ignazio F.Finazzi>cd "C:\Program Files (x86)\ireasoning\mibbrowser\bin

C:\Program Files (x86)\ireasoning\mibbrowser\bin>snmpwalk -v1 -c public 192.168.
1.105
Exception in thread "main" java.lang.NumberFormatException: For input string: "-
c"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at com.ireasoning.app.mibbrowser.qi.parseOptions(qi.java:291)
        at com.ireasoning.app.mibbrowser.qi.parseOptions(qi.java:265)
        at com.ireasoning.app.mibbrowser.SnmpWalk.main(SnmpWalk.java:15)
C:\Program Files (x86)\ireasoning\mibbrowser\bin>snmpwalk -v1 public 192.168.1.1
05
Exception in thread "main" java.lang.NumberFormatException: For input string: "p
ublic"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at com.ireasoning.app.mibbrowser.qi.parseOptions(qi.java:291)
        at com.ireasoning.app.mibbrowser.qi.parseOptions(qi.java:265)
        at com.ireasoning.app.mibbrowser.SnmpWalk.main(SnmpWalk.java:15)
C:\Program Files (x86)\ireasoning\mibbrowser\bin>snmpwalk -v1 192.168.1.105
Exception in thread "main" java.lang.NumberFormatException: For input string: "1
92.168.1.105"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at com.ireasoning.app.mibbrowser.qi.parseOptions(qi.java:291)
        at com.ireasoning.app.mibbrowser.qi.parseOptions(qi.java:265)
        at com.ireasoning.app.mibbrowser.SnmpWalk.main(SnmpWalk.java:15)
C:\Program Files (x86)\ireasoning\mibbrowser\bin>snmpwalk -v 1 192.168.1.105
¿Desea terminar el trabajo por lotes (S/N)? s

C:\Program Files (x86)\ireasoning\mibbrowser\bin>snmpwalk  192.168.1.105
time out
C:\Program Files (x86)\ireasoning\mibbrowser\bin>ping 192.168.1.105

Haciendo ping a 192.168.1.105 con 32 bytes de datos:
Respuesta desde 192.168.1.105: bytes=32 tiempo<1m TTL=128
Respuesta desde 192.168.1.105: bytes=32 tiempo<1m TTL=128
Respuesta desde 192.168.1.105: bytes=32 tiempo<1m TTL=128
Respuesta desde 192.168.1.105: bytes=32 tiempo<1m TTL=128

Estadísticas de ping para 192.168.1.105:
    Paquetes: enviados = 4, recibidos = 4, perdidos = 0
    (0% perdidos),
Tiempos aproximados de ida y vuelta en milisegundos:
    Mínimo = 0ms, Máximo = 0ms, Media = 0ms

C:\Program Files (x86)\ireasoning\mibbrowser\bin>snmpwalk -v1 -c public 192.168.
1.105
Exception in thread "main" java.lang.NumberFormatException: For input string: "-
c"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at com.ireasoning.app.mibbrowser.qi.parseOptions(qi.java:291)
        at com.ireasoning.app.mibbrowser.qi.parseOptions(qi.java:265)
        at com.ireasoning.app.mibbrowser.SnmpWalk.main(SnmpWalk.java:15)
C:\Program Files (x86)\ireasoning\mibbrowser\bin>snmpwalk public 192.168.1.105
java.net.UnknownHostException: public
java.net.UnknownHostException: public
        at java.net.InetAddress.getAllByName0(Unknown Source)
        at java.net.InetAddress.getAllByName(Unknown Source)
        at java.net.InetAddress.getAllByName(Unknown Source)
        at java.net.InetAddress.getByName(Unknown Source)
        at com.ireasoning.a.a.f.open(f.java:151)
        at com.ireasoning.a.a.f.open(f.java:137)
        at com.ireasoning.c.g.open(g.java:195)
        at com.ireasoning.c.g.<init>(g.java:137)
        at com.ireasoning.c.g.<init>(g.java:122)
        at com.ireasoning.c.g.<init>(g.java:157)
        at com.ireasoning.c.a.e.<init>(e.java:51)
        at com.ireasoning.c.a.f.<init>(f.java:129)
        at com.ireasoning.c.a.f.<init>(f.java:96)
        at com.ireasoning.app.mibbrowser.SnmpWalk.a(SnmpWalk.java:26)
        at com.ireasoning.app.mibbrowser.SnmpWalk.main(SnmpWalk.java:16)
C:\Program Files (x86)\ireasoning\mibbrowser\bin>snmpwalk -v1 public 192.168.1.1
05
Exception in thread "main" java.lang.NumberFormatException: For input string: "p
ublic"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at com.ireasoning.app.mibbrowser.qi.parseOptions(qi.java:291)
        at com.ireasoning.app.mibbrowser.qi.parseOptions(qi.java:265)
        at com.ireasoning.app.mibbrowser.SnmpWalk.main(SnmpWalk.java:15)
C:\Program Files (x86)\ireasoning\mibbrowser\bin>snmpwalk public 192.168.1.105
java.net.UnknownHostException: public
java.net.UnknownHostException: public
        at java.net.InetAddress.getAllByName0(Unknown Source)
        at java.net.InetAddress.getAllByName(Unknown Source)
        at java.net.InetAddress.getAllByName(Unknown Source)
        at java.net.InetAddress.getByName(Unknown Source)
        at com.ireasoning.a.a.f.open(f.java:151)
        at com.ireasoning.a.a.f.open(f.java:137)
        at com.ireasoning.c.g.open(g.java:195)
        at com.ireasoning.c.g.<init>(g.java:137)
        at com.ireasoning.c.g.<init>(g.java:122)
        at com.ireasoning.c.g.<init>(g.java:157)
        at com.ireasoning.c.a.e.<init>(e.java:51)
        at com.ireasoning.c.a.f.<init>(f.java:129)
        at com.ireasoning.c.a.f.<init>(f.java:96)
        at com.ireasoning.app.mibbrowser.SnmpWalk.a(SnmpWalk.java:26)
        at com.ireasoning.app.mibbrowser.SnmpWalk.main(SnmpWalk.java:16)
C:\Program Files (x86)\ireasoning\mibbrowser\bin>nit>(g.
Acceso denegado.

C:\Program Files (x86)\ireasoning\mibbrowser\bin>

What can i do????

**Comment by petrd** [comment]
Use the NET-SNMP (http://www.net-snmp.org/), works without problems.

Dne 8.10.2014 v 19:44 Kayzh3r napsal(a):
